### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by andot**
The touchscreen is working now.
image

The intel wifi is working now.
image

Update BOOTX64.efi to 5119.

Update Bluetooth driver to the latest unrelease version: https://github.com/zxystd/IntelBluetoothFirmware

Fixed USBPort.kext.

Use ACPIBatteryManager instead of SMCBatteryManager.

Update README.

### CODE REVIEW

**Comment by jschaeke** [comment]
I checked it out and tried it, Wifi, Battery and Touchscreen are working indeed.

**Review by Azkali — APPROVED** [review]
Tested working correctly, thanks for helping with touchscreen driver/issue !
Are you planning to add OC and automate it ? Can you join us on discord @andot ?

**Comment by Andiweli** [comment]
Can't confirm for WiFi :(
Either it doesn't load an website or with 1kb per sec...
Its correctly connected to my WiFi as usual. Tried with 4 differente WiFis as mentioned in the Readme.
Works only 1 out of 10 for me - sometimes WiFi keeps also disconnecting/connecting in a loop.

**Comment by andot** [comment]
> Can't confirm for WiFi :(
> Either it doesn't load an website or with 1kb per sec...
> Its correctly connected to my WiFi as usual. Tried with 4 differente WiFis as mentioned in the Readme.
> Works only 1 out of 10 for me - sometimes WiFi keeps also disconnecting/connecting in a loop.

Try to remove NullEthernet.kext, RtWlanU.kext and RtWlanU1827.kext.

Delete /Library/Preferences/SystemConfiguration/NetworkInterfaces.plist.

Delete all the interfaces in the Network of System Prefernces.

Reboot.

Add interfaces in the Network of System Prefernces.

**Comment by Andiweli** [comment]
Hi

Sadly not working...
WiFi keeps disconnecting every few seconds. 
It even shows the checkmark in the dropdown marking it as "connected" but internet is not available.  

Regards

**Comment by andot** [comment]
@stuermera try this latest version: https://github.com/Azkali/GPD-P2-MAX-Hackintosh/pull/37

**Pull request merged**
