### PR TITLE
Update Clover to 5127 to support Big Sur

### PR DESCRIPTION
**Pull request by andot**
I removed 

```
<key>framebuffer-fbmem</key>	
<data>AAAAAw==</data>	

<key>framebuffer-stolenmem</key>	
<data>AAAwAQ==</data>
```

in config.plist to support more higher resolution, such as 1440x900 HiDPI, 1680x1050 HiDPI.

but we shoud run:

```
setup_var_3 0x876 0x02
```

to set the DVMT Pre-Allocated from 32M to 64M.

### CODE REVIEW

**Comment by Azkali** [comment]
Hi, I need to reinstall my Hackintosh, will review while installing :+1: 
We should consider upgrading to OpenCore soon.
Thanks for the pull request

**Comment by andot** [comment]
You can use this EFI update to upgrade MacOS from Catalina to Big Sur without reinstall.😁

**Comment by Azkali** [comment]
I nuked my hackintosh by accident so I need to actually reinstall it completely

**Comment by andot** [comment]
it's so pity 😂

**Comment by wqianglxf** [comment]
Thank you for sharing @andot your upgrade to bigsur 1.11. There is no exception. It took 10 minutes to load the login interface. Finally, it was loaded automatically. Very happy!
After the upgrade, I used it. Except for FCP, my software was not re installed.
Questions:
1. Why are all the boot parameters gone? Are they unnecessary or forgotten?
2. The Intel WiFi driver airportitlwm I used before can't be used. This driver is better than itlwm in terms of adaptation. When catalida was loaded, I successfully added io80211family. However, WiFi could not find the network after upgrading. If io80211family was loaded, the boot would be stuck. seek help!
3. Bluetooth, the headset can, but the mouse connection will automatically disconnect, unable to use. I thought the upgrade would solve this problem, but I didn't think it would. If you can use the Airportitlwm driver, maybe you can (Z490i desktop I am also the case, but with this driver, Razer mouse connection).
4. I hope @Azkali your OpenCORE can solve these problems, thank you

**Comment by andot** [comment]
1. The boot parameters is unnecessary.
2. Airportitlwm is beta version, and itlwm is stable version. The airportitlwm sometimes can't work, so I put itlwm in EFI, but you can change it by yourself.
3. if you like Airportitlwm, you can try [AirportItlwm_v1.0_Beta_BigSur.kext.zip](https://heliport.bat-bat.workers.dev/https://github.com/OpenIntelWireless/itlwm/releases/download/v1.1.0/AirportItlwm_v1.0_Beta_BigSur.kext.zip)
4. OpenCORE can't solve these problems. These are caused by drivers. But you can try the latest alpha version wifi driver: https://github.com/OpenIntelWireless/itlwm/releases, it maybe can solve these problems.

**Comment by wqianglxf** [comment]
Today, when I turn on my computer, the following problems appear:
rtc read failure 1 bytes from 180 e00002c2
image

**Comment by wqianglxf** [comment]
> Today, when I turn on my computer, the following problems appear:
> rtc read failure 1 bytes from 180 e00002c2
> image

@andot 这个问题在毫无预照的情况下出现。我用的是您的EFI，之前都在正常使用。有2天没有开机，今天开机的时候就出现这个问题。不清楚是什么原因，期待您的回复！

**Comment by Azkali** [comment]
OpenCore 0.6.5 + Big Sur coming soon. I will put Clover to another branch and will make OpenCore the default one. Stay tuned for the update !

**Comment by Azkali** [comment]
Uploaded new branch will merge clover into master and move it to Clover branch. OpenCore is a WIP for now, many things are still broken. I will update the build in the following days.

**Pull request merged**
